version: "3.1"
services:
    db:
        image: mariadb:10.1
        container_name: docker-base-db
        working_dir: /application
        volumes:
            - ./volume/db/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    php:
        build: php-fpm
        container_name: docker-base-php
        working_dir: /application
        volumes:
            - ${APP_PATH}:/application
            - ./php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
            - ./volume/logs/symfony:/application/app/logs

    webserver:
      image: nginx:alpine
      container_name: docker-base-webserver
      working_dir: /application
      volumes:
          - ${APP_PATH}:/application
          - ./webserver/nginx.conf:/etc/nginx/conf.d/default.conf
          - ./volume/logs/nginx/:/var/log/nginx
      ports:
          - "80:80"
